Repository developer-student-clubs/npmBox, pull requests merged in 2022-10, with the labels that each got.

#6 Include Uid module
  README.md
  Uid/README.md
  Uid/uid.js
  package-lock.json
  package.json
Labels: documentation, good first issue, changes requested

#9 Documentation modified
  Uid/README.md
  Uid/uid.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#32 jsonwebtoken
  jsonwebtoken/README.md
  jsonwebtoken/jsonwebtoken.js
Labels: hacktoberfest, hacktoberfest-accepted

#54 Update README.md
  ora/README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#55 chalk module added
  chalk/README.md
  chalk/chalk.js
  package-lock.json
  package.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#70 Added Prisma Authentication Example & Updated README
  README.md
  prisma/authentication_example_using_prisma/.env
  prisma/authentication_example_using_prisma/controllers/postControllers.js
  prisma/authentication_example_using_prisma/controllers/userController.js
  prisma/authentication_example_using_prisma/helpers/getJwtToken.js
  prisma/authentication_example_using_prisma/index.js
  prisma/authentication_example_using_prisma/middlewares/isLoggedIn.js
  prisma/authentication_example_using_prisma/package-lock.json
  prisma/authentication_example_using_prisma/package.json
  prisma/authentication_example_using_prisma/prisma/index.js
  prisma/authentication_example_using_prisma/prisma/schema.prisma
  prisma/authentication_example_using_prisma/routes/postRoutes.js
  prisma/authentication_example_using_prisma/routes/userRoutes.js
  prisma/authentication_example_using_prisma/utils/cookieToken.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
